### ISSUE TITLE
[Spike] Investigate changes required to support an additional domain (defenseunicorns.com) in the uds.is environment

### ISSUE THREAD

**Issue by andrewg-xyz** [defenseunicorns/uds-appstore#204]
When live, UDS Marketplace will be accessible at https://apps.defenseunicorns.com

Ideally, UDS Marketplace would be deployed to the uds.is environment, with a modification to the uds-package custom resource i.e.
```
apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: uds-marketplace
  namespace: {{ .Release.Namespace }}
spec:
  network:
    expose:
      - service: uds-marketplace
        ...
        gateway: super-special-gateway-maybe
...
```
